# Generated by Django 4.1 on 2022-10-19 12:46

import apps.MemoriseFerdowsApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_title', models.CharField(max_length=200, verbose_name='عنوان خاطره')),
                ('memory_text', models.TextField(verbose_name='متن خاطره')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='زمان ثبت مقاله')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفال')),
                ('user_registered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
            ],
            options={
                'verbose_name': 'خاطره',
                'verbose_name_plural': 'خاطرات',
                'db_table': 't_meomry',
            },
        ),
        migrations.CreateModel(
            name='MemoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MemoriseFerdowsApp.memory')),
                ('user_liked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_meomrylike',
            },
        ),
        migrations.CreateModel(
            name='MemoryGalley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_image_name', models.ImageField(upload_to=apps.MemoriseFerdowsApp.models.upload_gallery_image, verbose_name='تصویر خاطره')),
                ('memory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='MemoriseFerdowsApp.memory')),
            ],
            options={
                'db_table': 't_meomrygallery',
            },
        ),
    ]
