# Generated by Django 4.1.2 on 2022-10-26 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MemoriseFerdowsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='register_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='زمان ثبت خاطره'),
        ),
    ]
