# Generated by Django 4.1 on 2022-09-14 15:07

import apps.ArticleApp.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='مقاله عنوان')),
                ('image', models.ImageField(upload_to=apps.ArticleApp.models.image_path, verbose_name='تصویر')),
                ('short_text', models.TextField(verbose_name='متن خلاصه')),
                ('text', models.TextField(verbose_name='متن اصلی')),
                ('key_words', models.CharField(max_length=200, verbose_name='کلمات کلیدی')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ درج مقاله')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار مقاله')),
                ('update_date', models.DateField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('pdf_filename', models.CharField(max_length=200, verbose_name='فایل pdf')),
                ('view_number', models.PositiveBigIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'db_table': 't_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100, verbose_name='عنوان گروه مقاله')),
            ],
            options={
                'verbose_name': 'گروه مقاله',
                'verbose_name_plural': 'گروه مقاله ها',
                'db_table': 't_article_group',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('family', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='موبایل')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفال')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده ها',
                'db_table': 't_author',
            },
        ),
        migrations.CreateModel(
            name='ArticleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=apps.ArticleApp.models.image_path, verbose_name='تصویر')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'db_table': 't_article_gallery',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.author', verbose_name='نویسنده مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.articlegroup', verbose_name='گروه مقاله'),
        ),
    ]
