# Generated by Django 4.1 on 2022-09-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='ArticleApp.author', verbose_name='نویسنده مقاله'),
        ),
    ]
