# Generated by Django 4.1 on 2022-10-18 15:42

import apps.ArticleApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0002_remove_article_author_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegallery',
            name='images',
            field=models.ImageField(upload_to=apps.ArticleApp.models.image_path2, verbose_name='تصویر'),
        ),
    ]
