# Generated by Django 4.1.2 on 2022-10-26 18:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0003_alter_articlegallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='متن اصلی'),
        ),
    ]
