# Generated by Django 4.0.5 on 2022-10-05 21:07

import apps.WorkshopApp.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image_name', models.ImageField(upload_to=apps.WorkshopApp.models.workshok_image_path, verbose_name='تصویر اصلی')),
                ('date_time', models.DateTimeField(verbose_name='تاریخ و زمان برگزاری')),
                ('places', models.CharField(max_length=50, verbose_name='مکان برگزاری')),
                ('teacher', models.CharField(max_length=50, verbose_name='مدرس')),
                ('information', models.TextField(verbose_name='اطلاعات')),
                ('registration', models.TimeField(verbose_name='شرایط ثبت نام')),
                ('report_text', models.TextField(blank=True, null=True, verbose_name='متن گزارش')),
                ('view_number', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت کارگاه')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'ورکشاپ',
                'verbose_name_plural': 'ورکشاپها',
                'db_table': 't_workshop',
            },
        ),
        migrations.CreateModel(
            name='WorkshopStatus',
            fields=[
                ('status_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد وضعیت')),
                ('status_title', models.CharField(max_length=50, verbose_name='عنوان وضعیت')),
            ],
            options={
                'verbose_name': 'وضعیت ورکشاپ',
                'verbose_name_plural': 'وضعیت ورکشاپها',
                'db_table': 't_workshopstatus',
            },
        ),
        migrations.CreateModel(
            name='WorkshopGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.WorkshopApp.models.gallery_image_path, verbose_name='تصویر')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkshopApp.workshop', verbose_name='کارگاه')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'db_table': 't_workshopgallery',
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkshopApp.workshopstatus', verbose_name='وضعیت کارگاه'),
        ),
    ]
