# Generated by Django 4.1 on 2022-08-31 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=100, verbose_name='آدرس ایمیل')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع پیام')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_seen', models.BooleanField(default=False, verbose_name='وضعیت دیده شدن پیام')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت پیام')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'db_table': 't_message',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200, verbose_name='نام مکان')),
                ('description', models.TextField(default='توضیحات مکان', verbose_name='توضیحات')),
                ('place_image_name', models.ImageField(upload_to='photos/Place_image', verbose_name='تصویر')),
                ('visit_date_day', models.CharField(max_length=200, verbose_name='تاریخ بازدید')),
                ('visit_time', models.CharField(max_length=200, verbose_name='ساعت بازدید')),
                ('Terms_Conditions', models.TextField(verbose_name='قوانین و مقررات')),
                ('more_information', models.TextField(blank=True, max_length=500, null=True, verbose_name='اطلاعات بیشتر')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت مکان')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان ها',
                'db_table': 't_place',
            },
        ),
        migrations.CreateModel(
            name='VisitorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='نام نوع بازدید کننده')),
            ],
            options={
                'verbose_name': 'بازدید کننده',
                'verbose_name_plural': 'بازدید کنندگان',
                'db_table': 't_visitor_type',
            },
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='بهای بیلیط')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntroductionApp.place', verbose_name='مکان بازدید')),
                ('visitor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntroductionApp.visitortype', verbose_name='نوع بازدید کننده')),
            ],
            options={
                'verbose_name': 'بیلیت',
                'verbose_name_plural': 'بیلیت ها',
                'db_table': 't_price_ticket',
            },
        ),
    ]
